---
title: "Putin's approval ratings"
author: "Eemil Mitikka"
date: "2023-02-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Libraries

```{r}
library(here)
library(tidyverse)
library(lubridate)
library(showtext)
library(ggtext)

font_add_google("Roboto slab", family="roboto-slab")

showtext_auto()

oma <- function() {
  font <- "roboto-slab"
  theme_minimal() %+replace%
    theme(
      plot.title = element_text(
        family = font,
        size = 33,
        face = 'bold',
        hjust = 0,
        vjust = 2,
        color = "grey40",
        margin = margin(8,2,2,2)),
      plot.subtitle = element_text(
        family = font,
        face = 'bold',
        size = 26,
        hjust = 0,
        vjust = 2,
        margin = margin(8,2,2,2)),
      axis.title = element_text(
        family = font,
        size = 20),
      axis.text = element_text(
        family = font,
        face = 'bold',
        size = 18),
      axis.title.y = element_text(
        margin = margin(0,0,0,2),
        face = "bold",
        angle = 90),
      axis.text.x = element_text(
        margin = margin(5, b = 10)),
      axis.title.x = element_text(
        family = font,
        size = 18,
        face = "bold"),
      strip.text = element_text(face = "bold",
                                  size = 25,
                                margin = margin(2,2,2,2)),
      legend.title = element_text(
        family = font,
        size = 20,
        face = "bold.italic"),
      legend.text = element_text(
        family = font,
        size = 18,
        face = "bold"),
      plot.background = element_rect(fill = "#EEEDE4"),
      panel.grid.major = element_line(colour = "#CCCDC4"),
      panel.grid.minor = element_line(colour = "#CCCDC4"),
    )
}
```

# Data

```{r}
library(openxlsx)

df <- 
  here("data/state_institutions (6).xlsx") %>% 
  read.xlsx() %>% 
  slice(1, 3) %>% 
  rename(approval = 1)

df <- as.data.frame(t(df))
row.names(df) <- NULL

df <-
  df %>% 
  rename(date = 1,
         president_prc = 2) %>% 
  slice(-1) %>% 
  mutate(date = str_remove_all(date, "[*]"),
         date = str_remove_all(date, ".*-")) %>% 
  mutate(date2 = as.integer(date),
         date3 = as.Date(date2, origin = "1899-12-30"))

df2 <-
df %>% 
  filter(is.na(date2)) %>% 
  mutate(date4 = 
           case_when(
             date == "29.12.2017 (данные за 5 дней)" ~ "29.12.2017",
             date == "11.02.208" ~ "11.02.2008",
             date == "03.02.0219" ~ "03.02.2019",
             date == "01.05.2022\r\n" ~ "01.05.2022",
             TRUE ~ date),
         date5 = dmy(date4)) %>% 
  select(date5, president_prc) %>% 
  rename(date = date5)

df <-
  df %>% 
  filter(date2 != "NA") %>% 
  select(date3, president_prc) %>% 
  rename(date = date3)

df_final <- 
  rbind(df, df2)

df_final <- 
df_final %>% 
  mutate(appr_prc = round(as.double(president_prc), digits = 1))

df_vtsiom <-
  df_final %>% 
  mutate(vtsiom_appr = round(0.01*appr_prc, digits = 2)) %>% 
  select(date, vtsiom_appr)

```


```{r}
library(rvest)

levada_link <- "https://www.levada.ru/indikatory/odobrenie-organov-vlasti/"
levada_page <- read_html(levada_link)

levada_president <- levada_page %>% 
  html_nodes("table.datatable") %>% 
  html_table() %>% 
  .[[1]] %>% 
  as.data.frame()

rownames(levada_president) <- c("date", "approve", "dont_approve", "no_answer")

levada_president <- as.data.frame(t(levada_president))

levada_president <-
  levada_president %>% 
  separate(date, c("month", "year")) %>% 
  mutate(year = 
           case_when(
             year == "2" ~ "2000",
             year == "201" ~ "2010",
             year == "202" ~ "2020",
             TRUE ~ year
           )) %>% 
  mutate(date = make_date(year, month),
         approve = 0.01 * approve,
         dont_approve = 0.01 * dont_approve,
         no_answer = 0.01 * no_answer) %>% 
  select(date, approve:no_answer)

df_levada <-
  levada_president %>% 
    mutate(levada_appr = approve) %>% 
    select(date, levada_appr)
rownames(df_levada) <- NULL

# write.csv(df_levada, here("data/df_levada.csv"))


df_ratings <- merge(df_vtsiom, df_levada, by = "date", all = T)

df_ratings2 <- 
df_ratings %>% 
  gather(key = "poll", val = prc, vtsiom_appr:levada_appr)

levada <- "#042654"
vtsiom <- "#740002"

arrows <- data.frame(x1_end = as.Date("2000-08-12"),
                     x2_end = as.Date("2004-09-01"),
                     x3_end = as.Date("2008-07-04"),
                     x4_end = as.Date("2011-12-12"),
                     x5_end = as.Date("2014-03-01"),
                     x6_end = as.Date("2018-07-14"),
                     y_start = 0.46, y_end = 0.55,
                     y2_start = 0.78, y2_end = 0.85)

arrows <- arrows %>% 
  mutate(x1_start = x1_end + days(516),
         x2_start = x2_end + days(516),
         x3_start = x3_end + days(516),
         x4_start = x4_end + days(516),
         x5_start = x5_end + days(516),
         x6_start = x6_end + days(516),
         x7_end = as.Date("2022-02-24"),
         x7_start = x7_end - days(516))

kursk <- arrows$x1_start
beslan <- arrows$x2_start
georgia_war <- arrows$x3_start
ffe <- arrows$x4_start
crimea <- arrows$x5_start
pension <- arrows$x6_start
invasion <- arrows$x7_start
  
p1 <- 
ggplot(df_ratings2) +
  aes(x = date) +
  geom_line(data = df_ratings2[!is.na(df_ratings2$prc),],
            aes(y = prc, color = poll),
            size = 1.4,
            alpha = 0.5)  +
  scale_color_manual(
    name = toupper("Data source"),
                     values = c(levada_appr = "#3A88D2",
                                vtsiom_appr = vtsiom),
                     labels = c("Levada-Center", "VTsIOM")) +
  oma() +
  scale_x_date(date_breaks = "1 year", 
               date_labels = "%Y") +
  theme(axis.text.x = element_text(angle = 35)) +
  labs(title = toupper("Putin's presidential/pm approval ratings ('Yes'-%)"),
       y = NULL,
       x = toupper("year")) +
  scale_y_continuous(labels = scales::label_percent())

p2 <-
p1 +  
  geom_vline(xintercept = as.Date("2014-02-23"), linetype = 2, size = 1.2) +
  geom_vline(xintercept = as.Date("2022-02-24"), linetype = 2, size = 1.2) +
  geom_vline(xintercept = as.Date("2008-08-01"), linetype = 2, size = 1.2) +
  geom_vline(xintercept = as.Date("2000-08-12"), linetype = 2, size = 1.2) +
  geom_vline(xintercept = as.Date("2011-12-04"), linetype = 2, size = 1.2) +
  geom_vline(xintercept = as.Date("2018-07-01"), linetype = 2, size = 1.2) +
  geom_vline(xintercept = as.Date("2004-09-01"), linetype = 2, size = 1.2) +
  geom_curve(aes(x = x1_start, y = y_start, xend = x1_end, yend = y_end),
    data = arrows, arrow = arrow(length = unit(0.03, "npc"))) + 
  geom_curve(aes(x = x2_start, y = y_start, xend = x2_end, yend = y_end),
    data = arrows, arrow = arrow(length = unit(0.03, "npc"))) +
  geom_curve(aes(x = x3_start, y = y_start, xend = x3_end, yend = y_end),
    data = arrows, arrow = arrow(length = unit(0.03, "npc"))) +
  geom_curve(aes(x = x4_start, y = y_start, xend = x4_end, yend = y_end),
    data = arrows, arrow = arrow(length = unit(0.03, "npc"))) +
  geom_curve(aes(x = x5_start, y = y_start, xend = x5_end, yend = y_end),
    data = arrows, arrow = arrow(length = unit(0.03, "npc"))) +
  geom_curve(aes(x = x6_start, y = y_start, xend = x6_end, yend = y_end),
    data = arrows, arrow = arrow(length = unit(0.03, "npc"))) +
  geom_curve(aes(x = x7_start, y = y2_start, xend = x7_end, yend = y2_end),
    data = arrows, arrow = arrow(length = unit(0.03, "npc")), curvature = -0.3) +
  labs(subtitle = "DATA SOURCE: <span style = 'color:#3A88D2;'>Levada-Center</span>, <span style = 'color:#740002'>VTsIOM</span>") +
  theme(panel.grid.major = element_blank(),
        plot.subtitle = element_markdown(),
        legend.position = "none") +
  annotate("text", y = 0.4, x = kursk, label = "Kursk\nsubmarine\ndisaster", size = 5) +
  annotate("text", y = 0.4, x = beslan, label = "Beslan\nschool\nsiege", size = 5) +
  annotate("text", y = 0.4, x = georgia_war, label = "Russo-\nGeorgian\nWar", size = 5) +
  annotate("text", y = 0.4, x = ffe, label = "2011\nelection\nprotests", size = 5) +
  annotate("text", y = 0.4, x = crimea, label = "Annexation\nof\nCrimea", size = 5) + 
  annotate("text", y = 0.4, x = pension, label = "Pension\nreform\nprotests", size = 5) + 
  annotate("text", y = 0.75, x = invasion, label = "Invasion of\nUkraine", size = 5)

# ggsave(here("img/putins_ratings.jpeg"),
#        width = 17, height = 9)





```

